const companyData = [
    { id: 1, name: "PosterMyWall", industry: "IT" },
    { id: 2, name: "GoSaaS, Inc.", industry: "IT" },
    { id: 3, name: "Zaltech AI", industry: "IT" },
    { id: 4, name: "Dubizzle Labs", industry: "IT" },
    { id: 5, name: "Leverify LLC (Zaman Technologies (SMC-Pvt) Ltd)", industry: "E-Commerce" },
    { id: 6, name: "Tajir", industry: "E-Commerce" },
    { id: 7, name: "Data Science Dojo", industry: "Ed-Tech" },
    { id: 8, name: "Educative Axis SMC Ltd", industry: "Ed-Tech" },
    { id: 9, name: "LUMSx", industry: "Ed-Tech" },
    { id: 10, name: "My Tutor Source", industry: "Ed-Tech" },
    { id: 11, name: "Careem", industry: "Engineering" },
    { id: 12, name: "National Engineering Services Pakistan (NESPAK)", industry: "Engineering" },
    { id: 13, name: "Giant Group", industry: "Fin-Tech" },
    { id: 14, name: "NayaPay (Pvt) Ltd", industry: "Fin-Tech" },
    { id: 15, name: "S&P Global", industry: "Fin-Tech" },
    { id: 16, name: "Telenor Microfinance Bank", industry: "Fin-Tech" },
    { id: 17, name: "VeriPark", industry: "Fin-Tech" },
    { id: 18, name: "Zindigi", industry: "Fin-Tech" },
    { id: 19, name: "Medcare MSO", industry: "Health-Tech" },
    { id: 20, name: "7Vals", industry: "IT" },
    { id: 21, name: "Aerodyne Group", industry: "IT" },
    { id: 22, name: "Afiniti Software Solutions Pvt. Ltd.", industry: "IT" },
    { id: 23, name: "AlphaBOLD", industry: "IT" },
    { id: 24, name: "AMIGO SOFTWARE", industry: "IT" },
    { id: 25, name: "ArhamSoft (Pvt) Ltd.", industry: "IT" },
    { id: 26, name: "AutoLeap Incorporated", industry: "IT" },
    { id: 27, name: "Big Entities Pvt. Ltd.", industry: "IT" },
    { id: 28, name: "Canyon Games", industry: "IT" },
    { id: 29, name: "Carbonteq", industry: "IT" },
    { id: 30, name: "Clustox", industry: "IT" },
    { id: 31, name: "CodingCops", industry: "IT" },
    { id: 32, name: "Confiz Ltd", industry: "IT" },
    { id: 33, name: "Conrad Labs", industry: "IT" },
    { id: 34, name: "CureMD", industry: "IT" },
    { id: 35, name: "Deline Media Group of Companies", industry: "IT" },
    { id: 36, name: "DevBatch", industry: "IT" },
    { id: 37, name: "Devigital Systems", industry: "IT" },
    { id: 38, name: "Enlatics", industry: "IT" },
    { id: 39, name: "Finz Games Private Limited", industry: "IT" },
    { id: 40, name: "FiveRivers Technologies", industry: "IT" },
    { id: 41, name: "FRAG Games", industry: "IT" },
    { id: 42, name: "Gaditek", industry: "IT" },
    { id: 43, name: "Gamivision", industry: "IT" },
    { id: 44, name: "HR Force", industry: "IT" },
    { id: 45, name: "i2c inc", industry: "IT" },
    { id: 46, name: "ibex.", industry: "IT" },
    { id: 47, name: "InvoZone.Pvt.Ltd", industry: "IT" },
    { id: 48, name: "Jaffer Business Systems (Pvt) Ltd", industry: "IT" },
    { id: 49, name: "Linked Matrix", industry: "IT" },
    { id: 50, name: "Machine Learning 1", industry: "IT" },
    { id: 51, name: "NetSol Technologies", industry: "IT" },
    { id: 52, name: "Nextbridge Ltd", industry: "IT" },
    { id: 53, name: "OCloud Solutions", industry: "IT" },
    { id: 54, name: "PakWheels.com", industry: "IT" },
    { id: 55, name: "Prismatic Technologies limited", industry: "IT" },
    { id: 56, name: "PureLogics", industry: "IT" },
    { id: 57, name: "Pursue Today HomoDeus LLP", industry: "IT" },
    { id: 58, name: "RepairDesk", industry: "IT" },
    { id: 59, name: "Rolustech", industry: "IT" },
    { id: 60, name: "Royal Cyber", industry: "IT" },
    { id: 61, name: "SAGE FREIGHT PAK SMC PRIVATE LIMITED", industry: "IT" },
    { id: 62, name: "Salesflo Pvt Ltd.", industry: "IT" },
    { id: 63, name: "Senarios Pvt Ltd", industry: "IT" },
    { id: 64, name: "Septem Systems", industry: "IT" },
    { id: 65, name: "SlashNext Pvt. Limited", industry: "IT" },
    { id: 66, name: "Softaims", industry: "IT" },
    { id: 67, name: "Soliton Technologies Pvt Ltd", industry: "IT" },
    { id: 68, name: "Speed Tech Services (Private) Limited", industry: "IT" },
    { id: 69, name: "Speridian Technologies", industry: "IT" },
    { id: 70, name: "Spur Solutions Private Limited", industry: "IT" },
    { id: 71, name: "SSI (Strategic Systems International)", industry: "IT" },
    { id: 72, name: "Stack labs (Creative Chaos)", industry: "IT" },
    { id: 73, name: "Talverse", industry: "IT" },
    { id: 74, name: "TechBazaar", industry: "IT" },
    { id: 75, name: "TechForge", industry: "IT" },
    { id: 76, name: "Techlogix Pakistan Private Limited", industry: "IT" },
    { id: 77, name: "tkxel", industry: "IT" },
];

export default companyData;